language: node_js

node_js:
  - "10"

cache:
  directories:
    "node_modules"

script:
  - npm test
  - npm build

deploy:
  provider: pages
  github-token: a25c59b7c73fb2a95f299225b61caf163c42ac80
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
