language: node_js

node_js:
  - "10"

cache:
  directories:
    "node_modules"

script:
  - npm test
  - npm build

deploy:
  provider: pages
  github-token: 
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
