language: node_js

node_js:
  - "10"

cache:
  directories:
    "node_modules"

script:
  - npm test
  - npm run build
  - npm run deploy

deploy:
  provider: pages
  github-token: $GH_TOKEN
  skip_cleanup: true
  keep-history: true
  local_dir: public
  on:
    branch: master
